import type { Block } from 'payload';

export const ChallengesBlock: Block = {
  slug: 'challenges-block',
  labels: { singular: 'Challenges block', plural: 'Challenges blocks' },
  interfaceName: 'ChallengesBlockFields',
  fields: [
    {
      label: 'Title',
      localized: true,
      name: 'title',
      required: true,
      type: 'textarea',
    },
    {
      label: 'Description',
      localized: true,
      name: 'description',
      required: false,
      type: 'textarea',
    },
    {
      fields: [
        {
          label: 'Card title',
          localized: true,
          name: 'title',
          required: true,
          type: 'text',
        },
        {
          label: 'Card description',
          localized: true,
          name: 'description',
          required: false,
          type: 'textarea',
        },
        {
          admin: { description: 'Optional solid background color (CSS value, e.g. #EAF6F1).' },
          label: 'Background color',
          localized: false,
          name: 'backgroundColor',
          required: false,
          type: 'text',
        },
        {
          admin: { description: 'Optional background image for the card.' },
          label: 'Background image',
          name: 'backgroundImage',
          relationTo: 'media',
          localized: true,
          required: false,
          type: 'upload',
        },
        {
          label: 'Image',
          name: 'image',
          relationTo: 'media',
          localized: true,
          required: true,
          type: 'upload',
        },
        {
          admin: { description: 'Swap which side the image is anchored to.' },
          defaultValue: 'right',
          label: 'Image side',
          name: 'imageSide',
          options: [
            { label: 'Right', value: 'right' },
            { label: 'Left', value: 'left' },
          ],
          required: false,
          type: 'select',
        },
        {
          admin: { description: 'Image position on X axis inside its area (0–100).' },
          defaultValue: 50,
          label: 'Image position X',
          max: 100,
          min: 0,
          name: 'imagePosX',
          required: false,
          type: 'number',
        },
        {
          admin: { description: 'Image position on Y axis inside its area (0–100).' },
          defaultValue: 50,
          label: 'Image position Y',
          max: 100,
          min: 0,
          name: 'imagePosY',
          required: false,
          type: 'number',
        },
      ],
      label: 'Cards',
      labels: { singular: 'Card', plural: 'Cards' },
      minRows: 1,
      name: 'cards',
      required: true,
      type: 'array',
    },
  ],
};

