import type { Block } from 'payload';

import { link } from '@/fields/link';

export const DownloadAppBlock: Block = {
  slug: 'download-app-block',
  labels: { singular: 'Download app block', plural: 'Download app blocks' },
  interfaceName: 'DownloadAppBlockFields',
  fields: [
    {
      admin: {
        description: 'Optional background image for the whole block card.',
      },
      label: 'Background image',
      name: 'backgroundImage',
      relationTo: 'media',
      localized: true,
      required: false,
      type: 'upload',
    },
    {
      admin: {
        description: 'How the background image is fitted inside the card.',
      },
      defaultValue: 'cover',
      label: 'Background fit',
      name: 'backgroundFit',
      options: [
        { label: 'Cover', value: 'cover' },
        { label: 'Contain', value: 'contain' },
      ],
      required: false,
      type: 'select',
    },
    {
      admin: {
        description: 'Background position in percent (0..100).',
      },
      fields: [
        {
          defaultValue: 50,
          label: 'X (%)',
          max: 100,
          min: 0,
          name: 'backgroundPosX',
          required: false,
          type: 'number',
        },
        {
          defaultValue: 50,
          label: 'Y (%)',
          max: 100,
          min: 0,
          name: 'backgroundPosY',
          required: false,
          type: 'number',
        },
      ],
      label: 'Background position',
      name: 'backgroundPosition',
      type: 'group',
    },
    {
      label: 'Title',
      localized: true,
      name: 'title',
      required: true,
      type: 'textarea',
    },
    {
      label: 'Description',
      localized: true,
      name: 'description',
      required: false,
      type: 'textarea',
    },
    {
      label: 'Buttons title',
      localized: true,
      name: 'buttonsTitle',
      required: false,
      type: 'text',
    },
    {
      label: 'Image',
      name: 'image',
      relationTo: 'media',
      localized: true,
      required: true,
      type: 'upload',
    },
    {
      admin: {
        description:
          'Right-side image layout (size and position). Offsets are applied as translate(px) on the image wrapper.',
      },
      fields: [
        {
          admin: { description: 'Max width of the right-side image in pixels.' },
          defaultValue: 560,
          label: 'Max width (px)',
          max: 2000,
          min: 120,
          name: 'imageMaxWidthPx',
          required: false,
          type: 'number',
        },
        {
          admin: { description: 'Max height of the right-side image in pixels.' },
          defaultValue: 560,
          label: 'Max height (px)',
          max: 2000,
          min: 120,
          name: 'imageMaxHeightPx',
          required: false,
          type: 'number',
        },
        {
          admin: { description: 'Horizontal offset in pixels (positive moves right).' },
          defaultValue: 0,
          label: 'Offset X (px)',
          max: 2000,
          min: -2000,
          name: 'imageOffsetXPx',
          required: false,
          type: 'number',
        },
        {
          admin: { description: 'Horizontal offset in percent (positive moves right).' },
          defaultValue: 0,
          label: 'Offset X (%)',
          max: 200,
          min: -200,
          name: 'imageOffsetXPercent',
          required: false,
          type: 'number',
        },
        {
          admin: { description: 'Vertical offset in pixels (positive moves down).' },
          defaultValue: 0,
          label: 'Offset Y (px)',
          max: 2000,
          min: -2000,
          name: 'imageOffsetYPx',
          required: false,
          type: 'number',
        },
        {
          admin: { description: 'Vertical offset in percent (positive moves down).' },
          defaultValue: 0,
          label: 'Offset Y (%)',
          max: 200,
          min: -200,
          name: 'imageOffsetYPercent',
          required: false,
          type: 'number',
        },
      ],
      label: 'Right-side image layout',
      name: 'imageLayout',
      type: 'group',
    },
    {
      fields: [
        link({
          appearances: false,
          overrides: { label: 'iOS link' },
        }),
        {
          admin: { description: 'Optional icon shown inside the iOS button (e.g. Apple logo).' },
          label: 'iOS icon',
          name: 'icon',
          relationTo: 'media',
          localized: true,
          required: false,
          type: 'upload',
        },
        {
          label: 'Button style',
          name: 'variant',
          type: 'select',
          required: false,
          defaultValue: 'dark',
          options: [
            { label: 'Dark (black)', value: 'dark' },
            { label: 'Light (white)', value: 'light' },
          ],
        },
      ],
      label: 'iOS button',
      name: 'iosButton',
      required: true,
      type: 'group',
    },
    {
      fields: [
        link({
          appearances: false,
          overrides: { label: 'Android link' },
        }),
        {
          admin: { description: 'Optional icon shown inside the Android button (e.g. Google Play logo).' },
          label: 'Android icon',
          name: 'icon',
          relationTo: 'media',
          localized: true,
          required: false,
          type: 'upload',
        },
        {
          label: 'Button style',
          name: 'variant',
          type: 'select',
          required: false,
          defaultValue: 'light',
          options: [
            { label: 'Dark (black)', value: 'dark' },
            { label: 'Light (white)', value: 'light' },
          ],
        },
      ],
      label: 'Android button',
      name: 'androidButton',
      required: true,
      type: 'group',
    },
  ],
};

